stages:
  - build_mpy

image: ubuntu:latest

build_mpy:
  stage: build_mpy
  script:
    - echo "This job builds something."
    - apt install git make build-essential
    - git clone https://github.com/micropython/micropython.git
    - cd micropython/mpy_cross
    - make
