stages:
  - setup
  - build
  - deploy

image: ubuntu:latest

setup:
  stage: setup
  script:
    - echo "This job builds something."
    - apt update
    - apt install -y git make build-essential python3
    - rm -r micropython
    - git clone https://github.com/micropython/micropython.git
    - cd micropython/mpy-cross
    - make
  cache:
    key: "changeme-to-recompute"
    paths:
      - micropython/mpy-cross/

build:
  stage: build
  dependencies:
    - setup
  cache:
    key: "changeme-to-recompute"
    paths:
      - micropython/mpy-cross/
  script:
    - |
      for file in Robi42Lib/**/*.py; do
        micropython/mpy-cross/build/mpy-cross $file
      done
      for file in Robi42Lib/**/*.mpy; do
        mkdir -p build/$(dirname $file)
      done
      for file in Robi42Lib/**/*.mpy; do
        cp $file build/$file
      done
      tar -cvf artifacts.tar build/
      echo '{"commit": "$CI_COMMIT_SHA", "branch": "$CI_COMMIT_REF_NAME", "date": "$CI_COMMIT_TIMESTAMP"}' > meta.json
  artifacts:
    paths:
      - meta.json
      - artifacts.tar
      - "build/"

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file asdf.mpy "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/0.0.1/asdf.mpy"'
