stages:
  - build_mpy

image: ubuntu:latest

build_mpy:
  stage: build_mpy
  script:
    - echo "This job builds something."
    - apt update
    - apt install -y git make build-essential python3
    - git clone https://github.com/micropython/micropython.git
    - cd micropython/mpy-cross
    - make
    - echo "print('asdf')" > asdf.py
    - build/mpy-cross asdf.py
    - cat asdf.mpy
